/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carsproject;

import com.mycompany.carsproject.Object.Car;
import com.mycompany.carsproject.Object.Car_DAO;
import com.mycompany.carsproject.Object.Car_on_rent;
import com.mycompany.carsproject.Object.Car_on_rent_DAO;
import com.mycompany.carsproject.Object.Customer_DAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manhl
 */
public class RentalForm extends javax.swing.JFrame {
    Customer_DAO customerDAO = new Customer_DAO();
    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        displayActiveCarsOnTable();
        displayActiveCarsOnRentOnTable();
        populateCustomerIDs();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
     private void displayActiveCarsOnTable() {
        Car_DAO carDAO = new Car_DAO();
        List<Car> activeCars = carDAO.getAllActiveCars();
        DefaultTableModel clear = (DefaultTableModel)Avaiable_cars.getModel();
        clear.setRowCount(0);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Rent ID");
        model.addColumn("Brand");
        model.addColumn("Model");
        model.addColumn("License Plate");
        model.addColumn("Price");

        for (Car car : activeCars) {
            model.addRow(new Object[]{
                    car.getCarID(),
                    car.getBrand(),
                    car.getModel(),
                    car.getLicensePlate(),
                    car.getPrice()
            });
        }

        Avaiable_cars.setModel(model);
    }
      private void displayActiveCarsOnRentOnTable() {
        Car_on_rent_DAO car_rentedDAO = new Car_on_rent_DAO();
        List<Car_on_rent> Cars_rented = car_rentedDAO.getAllCarOnRentWithFeesFromFunction();
        DefaultTableModel clear = (DefaultTableModel)Cars_on_rent.getModel();
        clear.setRowCount(0);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Rent ID");
        model.addColumn("Car ID");
        model.addColumn("Customer ID");
        model.addColumn("Ngày thuê");
        model.addColumn("Ngày hẹn trả");
        model.addColumn("Tổng tiền");
        
        for (Car_on_rent car : Cars_rented) {
            model.addRow(new Object[]{
                    car.getRentID(),
                    car.getCarID(),
                    car.getCustomerID(),
                    car.getRentDate(),
                    car.getReturnDate(),
                    car.getPrice()
            });
        }

        Cars_on_rent.setModel(model);
    }
    private void populateCustomerIDs() {
    // Get all customer IDs from the database
        List<String> customerIDs = customerDAO.getAllCustomerIDs();

        // Clear existing items in the JComboBox
        Customer_ID.removeAllItems();

    // Add retrieved customer IDs to the JComboBox
        for (String customerID : customerIDs) {
            Customer_ID.addItem(customerID);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rent_ID = new javax.swing.JTextField();
        Car_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Customer_ID = new javax.swing.JComboBox<>();
        Rent = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cars_on_rent = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Avaiable_cars = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PRICE_SUM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Rent_date = new com.toedter.calendar.JDateChooser();
        Return_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Thuê Xe");

        jLabel2.setText("Mã hóa đơn");

        Rent_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_IDActionPerformed(evt);
            }
        });

        Car_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_IDActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã xe");

        jLabel4.setText("Mã khách hàng");

        jLabel5.setText("Ngày thuê");

        jLabel6.setText("Ngày hẹn trả");

        Customer_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Customer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_IDActionPerformed(evt);
            }
        });

        Rent.setText("Thuê");
        Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentActionPerformed(evt);
            }
        });

        Update.setText("Làm mới");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Back.setText("< Trở về");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Cars_on_rent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã xe", "Mã khách hàng", "Ngày thuê", "Ngày hẹn trả", "Tổng"
            }
        ));
        jScrollPane1.setViewportView(Cars_on_rent);

        Avaiable_cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Nhãn hiệu", "Dòng", "Biển kiếm soát", "Giá"
            }
        ));
        Avaiable_cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avaiable_carsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Avaiable_cars);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Xe có sẵn");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Xe đang được thuê");

        jLabel7.setText("Giá thuê (1 ngày)");

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(198, 198, 198))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Rent_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                    .addComponent(Car_ID, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Customer_ID, javax.swing.GroupLayout.Alignment.LEADING, 0, 113, Short.MAX_VALUE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(PRICE_SUM, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Rent_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Return_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8))))
                                        .addGap(18, 18, 18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(340, 340, 340)
                                .addComponent(jLabel1)))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rent_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Car_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(Rent_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Return_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PRICE_SUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         choiceForm choiceform = new choiceForm();

    // Hiển thị JFrame manageCustomers
        choiceform.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentActionPerformed
        // TODO add your handling code here:
                                           
    // Lấy dữ liệu từ các thành phần trên giao diện
        String carID = Car_ID.getText();
        String customerID = (String) Customer_ID.getSelectedItem();
        String rentID = Rent_ID.getText();
        java.sql.Date rentDate;
        java.sql.Date returnDate;
        if(Rent_date.getDate()==null || Return_date.getDate()==null)
        {
            jLabel10.setText("Vui lòng điền đầy đủ ngày ");
        }
        else{
        rentDate = new java.sql.Date(Rent_date.getDate().getTime());
        returnDate = new java.sql.Date(Return_date.getDate().getTime()); 
        
        while(true)
        {
        if(carID.isBlank() || customerID.isBlank() || rentID.isBlank())
        {
            jLabel10.setText("Vui lòng điền đầy đủ thông tin");
            break;
        }
        if(rentDate.after(returnDate))
        {
            jLabel10.setText("Ngày hẹn trả không được nhỏ hơn ngày thuê");
            break;
        }
        else
        {
            // Tạo đối tượng Car_on_rent
        Car_on_rent carOnRent = new Car_on_rent(carID, customerID, rentID, rentDate, returnDate);

    // Thêm hóa đơn thông qua đối tượng DAO
        Car_on_rent_DAO carOnRentDAO = new Car_on_rent_DAO();
        carOnRentDAO.addCarOnRent(carOnRent);
        jLabel10.setText("");

    // Cập nhật lại bảng Cars_on_rent (nếu cần)
        displayActiveCarsOnTable();
        displayActiveCarsOnRentOnTable();
        break;
        }
        }

    //updateCarsOnRentTable(); // Hàm này cần phải được triển khai để cập nhật hiển thị trên bảng Cars_on_rent
        }
    }//GEN-LAST:event_RentActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        displayActiveCarsOnTable();
        displayActiveCarsOnRentOnTable();
    
    }//GEN-LAST:event_UpdateActionPerformed

    private void Customer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_IDActionPerformed

    private void Car_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Car_IDActionPerformed
      
    
    private void Avaiable_carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avaiable_carsMouseClicked
        // TODO add your handling code here:
        int selectedRow = Avaiable_cars.getSelectedRow();

        if (selectedRow != -1) {
        // Lấy giá trị của cột Car ID (giả sử là cột thứ 0)
            Object carIDObject = Avaiable_cars.getValueAt(selectedRow, 0);
            Object PRICEObject = Avaiable_cars.getValueAt(selectedRow, 4);
//            java.sql.Date rentDate = new java.sql.Date(Rent_date.getDate().getTime());
//            java.sql.Date returnDate = new java.sql.Date(Return_date.getDate().getTime());
            
            if (carIDObject != null) {
                String carID = carIDObject.toString();
                Car_ID.setText(carID);
                String price = PRICEObject.toString();
                PRICE_SUM.setText(price);
            }
        }
    }//GEN-LAST:event_Avaiable_carsMouseClicked

    private void Rent_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Avaiable_cars;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Car_ID;
    private javax.swing.JTable Cars_on_rent;
    private javax.swing.JComboBox<String> Customer_ID;
    private javax.swing.JTextField PRICE_SUM;
    private javax.swing.JButton Rent;
    private javax.swing.JTextField Rent_ID;
    private com.toedter.calendar.JDateChooser Rent_date;
    private com.toedter.calendar.JDateChooser Return_date;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}